on: [push]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - uses: actions/checkout@v1
      - run: |
          FLAGS=
          [ "${{ matrix.goos }}" = "windows" ] && FLAGS='-ldflags -H=windowsgui'
      - env:
          GOPROXY: "https://proxy.golang.org"
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build $FLAGS ./cmd/coub-archive
      - run: |
          [ "${{ matrix.goos }}" = "darwin" ] && ./build/package/package.sh