on: [push]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - uses: actions/checkout@v1
      - env:
          GOPROXY: "https://proxy.golang.org"
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build ./cmd/coub-archive